"""creating banner table

Revision ID: cce23b230912
Revises: 842df13f6d01
Create Date: 2023-01-10 16:17:45.767514

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from app.db.utils import create_trigger_for_update


# revision identifiers, used by Alembic.
revision = 'cce23b230912'
down_revision = '842df13f6d01'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('banners',
                    sa.Column('id', postgresql.UUID(), server_default=sa.text(
                        'gen_random_uuid()'), nullable=False),
                    sa.Column('title', sa.String(length=50), nullable=False),
                    sa.Column('image', sa.String(), nullable=False),
                    sa.Column('start_date', sa.Date(), nullable=True),
                    sa.Column('end_date', sa.Date(), nullable=True),
                    sa.Column('created_at', sa.DateTime(timezone=True),
                              server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
                    sa.Column('updated_at', sa.DateTime(timezone=True),
                              server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
                    sa.Column('is_deleted', sa.Boolean(),
                              server_default=sa.text('false'), nullable=False),
                    sa.Column('deleted_at', sa.DateTime(
                        timezone=True), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('image'),
                    sa.UniqueConstraint('title'),
                    schema='dev'
                    )
    op.drop_constraint('employement_rewards_reward_id_fkey',
                       'employement_rewards', type_='foreignkey')
    op.drop_constraint('employement_rewards_employement_id_fkey',
                       'employement_rewards', type_='foreignkey')
    op.create_foreign_key(None, 'employement_rewards', 'employements', [
                          'employement_id'], ['id'], source_schema='dev', referent_schema='dev')
    op.create_foreign_key(None, 'employement_rewards', 'rewards', ['reward_id'], [
                          'id'], source_schema='dev', referent_schema='dev')
    op.drop_constraint('rewards_employement_id_fkey',
                       'rewards', type_='foreignkey')
    op.create_foreign_key(None, 'rewards', 'employements', ['employement_id'], [
                          'id'], source_schema='dev', referent_schema='dev')
    op.drop_constraint('user_rewards_citation_id_fkey',
                       'user_rewards', type_='foreignkey')
    op.drop_constraint('user_rewards_user_id_fkey',
                       'user_rewards', type_='foreignkey')
    op.drop_constraint('user_rewards_reward_id_fkey',
                       'user_rewards', type_='foreignkey')
    op.create_foreign_key(None, 'user_rewards', 'rewards', ['reward_id'], [
                          'id'], source_schema='dev', referent_schema='dev')
    op.create_foreign_key(None, 'user_rewards', 'users', ['citation_id'], [
                          'id'], source_schema='dev', referent_schema='dev')
    op.create_foreign_key(None, 'user_rewards', 'users', ['user_id'], [
                          'id'], source_schema='dev', referent_schema='dev')
    op.drop_constraint('users_group_id_fkey', 'users', type_='foreignkey')
    op.drop_constraint('users_employement_id_fkey',
                       'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'employements', ['employement_id'], [
                          'id'], source_schema='dev', referent_schema='dev')
    op.create_foreign_key(None, 'users', 'groups', ['group_id'], [
                          'id'], source_schema='dev', referent_schema='dev')
    # ### end Alembic commands ###
    _dll = create_trigger_for_update("banners")
    op.execute(_dll)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', schema='dev', type_='foreignkey')
    op.drop_constraint(None, 'users', schema='dev', type_='foreignkey')
    op.create_foreign_key('users_employement_id_fkey',
                          'users', 'employements', ['employement_id'], ['id'])
    op.create_foreign_key('users_group_id_fkey', 'users',
                          'groups', ['group_id'], ['id'])
    op.drop_constraint(None, 'user_rewards', schema='dev', type_='foreignkey')
    op.drop_constraint(None, 'user_rewards', schema='dev', type_='foreignkey')
    op.drop_constraint(None, 'user_rewards', schema='dev', type_='foreignkey')
    op.create_foreign_key('user_rewards_reward_id_fkey',
                          'user_rewards', 'rewards', ['reward_id'], ['id'])
    op.create_foreign_key('user_rewards_user_id_fkey',
                          'user_rewards', 'users', ['user_id'], ['id'])
    op.create_foreign_key('user_rewards_citation_id_fkey',
                          'user_rewards', 'users', ['citation_id'], ['id'])
    op.drop_constraint(None, 'rewards', schema='dev', type_='foreignkey')
    op.create_foreign_key('rewards_employement_id_fkey',
                          'rewards', 'employements', ['employement_id'], ['id'])
    op.drop_constraint(None, 'employement_rewards',
                       schema='dev', type_='foreignkey')
    op.drop_constraint(None, 'employement_rewards',
                       schema='dev', type_='foreignkey')
    op.create_foreign_key('employement_rewards_employement_id_fkey',
                          'employement_rewards', 'employements', ['employement_id'], ['id'])
    op.create_foreign_key('employement_rewards_reward_id_fkey',
                          'employement_rewards', 'rewards', ['reward_id'], ['id'])
    op.drop_table('banners', schema='dev')
    # ### end Alembic commands ###
