"""add function

Revision ID: db85a004d75a
Revises: 47719f28006e
Create Date: 2022-11-23 12:34:11.677232

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import DDL, event


# revision identifiers, used by Alembic.
revision = 'db85a004d75a'
down_revision = '47719f28006e'
branch_labels = None
depends_on = None


func_ = DDL(
    """
    CREATE OR REPLACE FUNCTION trigger_set_timestamp()
    RETURNS TRIGGER AS $$
    BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
    END;
    $$ LANGUAGE plpgsql;
"""
)

func_dele = DDL(
    """
    DROP FUNCTION IF EXISTS trigger_set_timestamp()
"""
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('employement_rewards_reward_id_fkey',
                       'employement_rewards', type_='foreignkey')
    op.drop_constraint('employement_rewards_employement_id_fkey',
                       'employement_rewards', type_='foreignkey')
    op.create_foreign_key(None, 'employement_rewards', 'rewards', ['reward_id'], [
                          'id'], source_schema='dev', referent_schema='dev')
    op.create_foreign_key(None, 'employement_rewards', 'employements', [
                          'employement_id'], ['id'], source_schema='dev', referent_schema='dev')
    op.drop_constraint('rewards_employement_id_fkey',
                       'rewards', type_='foreignkey')
    op.create_foreign_key(None, 'rewards', 'employements', ['employement_id'], [
                          'id'], source_schema='dev', referent_schema='dev')
    op.drop_constraint('user_rewards_user_id_fkey',
                       'user_rewards', type_='foreignkey')
    op.drop_constraint('user_rewards_reward_id_fkey',
                       'user_rewards', type_='foreignkey')
    op.create_foreign_key(None, 'user_rewards', 'rewards', ['reward_id'], [
                          'id'], source_schema='dev', referent_schema='dev')
    op.create_foreign_key(None, 'user_rewards', 'users', ['user_id'], [
                          'id'], source_schema='dev', referent_schema='dev')
    op.drop_constraint('users_group_id_fkey', 'users', type_='foreignkey')
    op.drop_constraint('users_employement_id_fkey',
                       'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'groups', ['group_id'], [
                          'id'], source_schema='dev', referent_schema='dev')
    op.create_foreign_key(None, 'users', 'employements', ['employement_id'], [
                          'id'], source_schema='dev', referent_schema='dev')
    # ### end Alembic commands ###
    op.execute(func_)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', schema='dev', type_='foreignkey')
    op.drop_constraint(None, 'users', schema='dev', type_='foreignkey')
    op.create_foreign_key('users_employement_id_fkey',
                          'users', 'employements', ['employement_id'], ['id'])
    op.create_foreign_key('users_group_id_fkey', 'users',
                          'groups', ['group_id'], ['id'])
    op.drop_constraint(None, 'user_rewards', schema='dev', type_='foreignkey')
    op.drop_constraint(None, 'user_rewards', schema='dev', type_='foreignkey')
    op.create_foreign_key('user_rewards_reward_id_fkey',
                          'user_rewards', 'rewards', ['reward_id'], ['id'])
    op.create_foreign_key('user_rewards_user_id_fkey',
                          'user_rewards', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'rewards', schema='dev', type_='foreignkey')
    op.create_foreign_key('rewards_employement_id_fkey',
                          'rewards', 'employements', ['employement_id'], ['id'])
    op.drop_constraint(None, 'employement_rewards',
                       schema='dev', type_='foreignkey')
    op.drop_constraint(None, 'employement_rewards',
                       schema='dev', type_='foreignkey')
    op.create_foreign_key('employement_rewards_employement_id_fkey',
                          'employement_rewards', 'employements', ['employement_id'], ['id'])
    op.create_foreign_key('employement_rewards_reward_id_fkey',
                          'employement_rewards', 'rewards', ['reward_id'], ['id'])
    # ### end Alembic commands ###
    op.execute(func_dele)
